### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by sespiros** [sespiros/go-telegram-garvis#1]
### Ideas
- [ ] Enable/Disable filters on demand
- [ ] Modifiable responses for caps filter
- [ ] Modifiable responses for tldr filter
- [ ] Storage wrapper class for handling multiple stacks for storage
- [ ] Logger wrapper class for handling different libraries of Loggers
- [x] Text filter: list and delete rules with command
- [x] Modifiable responses for text filter

### New Filter Ideas
- [ ] **Idle Filter**: send a message if the group is silent for a while (probably tied to a specific group)
